INSERT INTO municipalities (id, nome, provincia_id, area_km2, populacao) VALUES
(1, 'Belas', 1, NULL, NULL),
(2, 'Cacuaco', 1, NULL, NULL),
(3, 'Cazenga', 1, NULL, NULL),
(4, 'Kilamba Kiaxi', 1, NULL, NULL),
(5, 'Viana', 1, NULL, NULL),
(6, 'Mussulo', 1, NULL, NULL),
(7, 'Sambizanga', 1, NULL, NULL),
(8, 'Rangel', 1, NULL, NULL),
(9, 'Maianga', 1, NULL, NULL),
(10, 'Samba', 1, NULL, NULL),
(11, 'Camama', 1, NULL, NULL),
(12, 'Mulenvos', 1, NULL, NULL),
(13, 'Kilamba', 1, NULL, NULL),
(14, 'Hoji Ya Henda', 1, NULL, NULL),
(15, 'Ingombota', 1, NULL, NULL),
(16, 'Talatona', 1, NULL, NULL),
(17, 'Bula Atumba', 2, NULL, NULL),
(18, 'Dande', 2, NULL, NULL),
(19, 'Quibaxe', 2, NULL, NULL),
(20, 'Nambuangongo', 2, NULL, NULL),
(21, 'Pango Aluquém', 2, NULL, NULL),
(22, 'Ambriz', 2, NULL, NULL),
(23, 'Muxaluando', 2, NULL, NULL),
(24, 'Piri', 2, NULL, NULL),
(25, 'Quicunzo', 2, NULL, NULL),
(26, 'Úcua', 2, NULL, NULL),
(27, 'Panguila', 2, NULL, NULL),
(28, 'Barra do Dande', 2, NULL, NULL),
(29, 'Baía Farta', 3, NULL, NULL),
(30, 'Balombo', 3, NULL, NULL),
(31, 'Bocoio', 3, NULL, NULL),
(32, 'Caimbambo', 3, NULL, NULL),
(33, 'Catumbela', 3, NULL, NULL),
(34, 'Chongorói', 3, NULL, NULL),
(35, 'Cubal', 3, NULL, NULL),
(36, 'Ganda', 3, NULL, NULL),
(37, 'Lobito', 3, NULL, NULL),
(38, 'Benguela', 3, NULL, NULL),
(39, 'Egito Praia', 3, NULL, NULL),
(40, 'Chindumbo', 3, NULL, NULL),
(41, 'Dombe Grande', 3, NULL, NULL),
(42, 'Capupa', 3, NULL, NULL),
(43, 'Biópio', 3, NULL, NULL),
(44, 'Chila', 3, NULL, NULL),
(45, 'Chicuma', 3, NULL, NULL),
(46, 'Babaera', 3, NULL, NULL),
(47, 'Iambala', 3, NULL, NULL),
(48, 'Catengue', 3, NULL, NULL),
(49, 'Bolonguera', 3, NULL, NULL),
(50, 'Canhamela', 3, NULL, NULL);